import assert from 'assert'

export const SYNCHRONIZE_PRODUCTS_JOB_INTERVAL = Number(
  process.env.SUPPLIER_SYNCHRONIZE_PRODUCTS_JOB_INTERVAL_MS
)

export const WRITE_PRODUCTS_JOB_CRON_EXPRESSION =
  process.env.SUPPLIER_WRITE_PRODUCTS_JOB_CRON_EXPRESSION

assert.ok(
  !Number.isNaN(SYNCHRONIZE_PRODUCTS_JOB_INTERVAL),
  `Missing env variable 'SUPPLIER_SYNCHRONIZE_PRODUCTS_JOB_INTERVAL_MS'`
)

assert.ok(
  WRITE_PRODUCTS_JOB_CRON_EXPRESSION,
  `Missing env variable 'SUPPLIER_WRITE_PRODUCTS_JOB_CRON_EXPRESSION'`
)
