packageExtensions:
  '@grpc/grpc-js@*':
    dependencies:
      '@types/long': '*'
  '@atls/typeorm-logger@*':
    dependencies:
      typeorm: '*'
  '@atls/nestjs-gateway@*':
    dependencies:
      ws: '*'
  '@atls/nestjs-grpc-http-proxy@*':
    dependencies:
      express: '*'
  '@atls/nestjs-grpc-reflection@*':
    dependencies:
      long: '*'
      protobufjs: '*'
  '@graphql-mesh/store@*':
    dependencies:
      '@graphql-mesh/types': '*'
  '@graphql-mesh/types@*':
    dependencies:
      '@graphql-mesh/store': '*'
      '@envelop/core': '*'
  '@graphql-tools/graphql-tag-pluck@*':
    dependencies:
      '@vue/compiler-sfc': '*'
      svelte2tsx: '*'
      svelte: '*'
  '@graphql-typed-document-node/core@*':
    dependencies:
      graphql: '*'
  '@nestjs/common@*':
    dependencies:
      '@grpc/proto-loader': '*'
      cache-manager: '*'
      reflect-metadata: '*'
      rxjs: '*'
  '@nestjs/core@*':
    dependencies:
      '@nestjs/platform-express': '*'
      '@nestjs/websockets': '*'
      reflect-metadata: '*'
      rxjs: '*'
  '@nestjs/cqrs@*':
    dependencies:
      reflect-metadata: '*'
      rxjs: '*'
  '@nestjs/microservices@*':
    dependencies:
      '@grpc/grpc-js': '*'
      '@grpc/proto-loader': '*'
      '@nestjs/websockets': '*'
      mqtt: '*'
      reflect-metadata: '*'
      rxjs: '*'
      kafkajs: '*'
  '@nestjs/typeorm@*':
    dependencies:
      rxjs: '*'
  '@nestjs/websockets@*':
    dependencies:
      '@nestjs/platform-socket.io': '*'

yarnPath: .yarn/releases/yarn-0.0.1-git.20220605.hash-c4f9c8f.cjs
