version: '3.8'

services:
  yarn:
    image: node:16
    working_dir: /workspace
    volumes:
      - ./:/workspace
    entrypoint: yarn

  db:
    image: bitnami/postgresql
    environment:
      - POSTGRESQL_PASSWORD=password
      - POSTGRESQL_DATABASE=db
      - POSTGRESQL_USER=postgres
    ports:
      - 5432:5432

  synchronizer:
    image: node:16
    working_dir: /workspace
    volumes:
      - ./:/workspace
    entrypoint: yarn workspace @  synchronizer/service-entrypoint dev
    networks:
      - default
    environment:
      - DB_HOST=db
    depends_on:
      - db
    ports:
      - 50051:50051

  public-gateway:
    image: node:16
    working_dir: /workspace
    volumes:
      - ./:/workspace
    entrypoint: yarn workspace @gateway/public-gateway-entrypoint dev
    ports:
      - 3000:3000
    networks:
      - default
