version: '3.8'

services:
  yarn:
    image: node:16
    working_dir: /workspace
    volumes:
      - ./:/workspace
    entrypoint: yarn

  db:
    image: bitnami/postgresql
    environment:
      - POSTGRESQL_PASSWORD=password
      - POSTGRESQL_DATABASE=db
      - POSTGRESQL_USER=postgres
    ports:
      - 5432:5432

  synchronizer:
    image: node:16
    working_dir: /workspace
    volumes:
      - ./:/workspace
    entrypoint: yarn workspace @synchronizer/service-entrypoint dev
    networks:
      - default
    env_file:
      - .env
    environment:
      - DB_HOST=db
    depends_on:
      - db

  write-all-products-job:
    image: node:16
    working_dir: /workspace
    volumes:
      - ./:/workspace
    entrypoint: yarn workspace @synchronizer/write-all-products-job dev
    networks:
      - default
    environment:
      - DB_HOST=db
    env_file:
      - .env
    depends_on:
      - db
