import assert from 'assert'

export const SYNCHRONIZE_PRODUCTS_JOB_INTERVAL = Number(
  process.env.MARKETPLACE_SYNCHRONIZE_PRODUCTS_JOB_INTERVAL_MS
)

assert.ok(
  !Number.isNaN(SYNCHRONIZE_PRODUCTS_JOB_INTERVAL),
  `Missing env variable 'MARKETPLACE_SYNCHRONIZE_PRODUCTS_JOB_INTERVAL_MS'`
)
